#!/usr/bin/env bash
# A script that runs and terminates itself
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
echo $$ > /var/run/myscript.pid
while true; do
	echo "To infinity and beyond"
	sleep 2
done
