#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements.
temp_file=$(mktemp)
echo "127.0.0.2		localhost" >> $temp_file
echo "8.8.8.8		facebook.com" >> $temp_file
mv $temp_file /etc/hosts
